spring:
  shardingsphere:
    datasource:
      names: db0,db1
      db0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
        username: root
        password: 123456
      db1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
        username: root
        password: 123456
    sharding:
      default-database-strategy:
        inline:
          sharding-column: id
          algorithm-expression: db$->{id%2}
      tables:
        user:
          actual-data-nodes: db0.user_${0..1}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: user_$->{id%2}
        order_item:
          actual-data-nodes: db$->{0..1}.order_item_$->{0..1}
          table-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: order_item_$->{user_id%2}
        myorder:
          actual-data-nodes: db$->{0..1}.myorder_$->{0..1}
          table-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: myorder_$->{user_id%2}
        order:
          actual-data-nodes: db$->{0..1}.order_$->{0..1}
          table-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: order_$->{user_id%2}
        person:
          actual-data-nodes: db$->{0..1}.person_$->{0..1}
          table-strategy:
            inline:
              sharding-column: age
              algorithm-expression: person_$->{age%2}


mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.demo.pojo
  type-enums-package: com.example.demo.myenum